const express=require("express")
const router =express.Router()
const auth = require("../middleware/middleware")
const userController = require("../controller/user.controller")
const blogController =require("../controller/blog.controller")
const moduleController = require("../controller/todolist.controller")
router.post("/signUp",userController.signUp)
router.post("/signIn",userController.signIn)
router.post("/updateUser/:id",auth,userController.updateUserDetails)
router.delete("/deleteUser/:id",auth,userController.deleteUser)
router.get("/search",auth,userController.searchName)

router.post("/blog",auth,blogController.createBlog)
router.get('/viewBlog/:id',auth,blogController.getBolg)
router.put('/updateBlog/:id',auth,blogController.updateBlogDetails)
router.delete("/deleteBlog/:id",auth,blogController.deleteBlog)
router.get("/getBlogCount/:id",blogController.blogCount)
router.post("/blogCategory",auth,blogController.createBlogCategories)

router.get("/view/:id",auth,moduleController.viewToDoList)
router.post("/createTodo",auth,moduleController.createToDoList)
router.put("/updateToDo/:id",auth,moduleController.updateToDoList)
router.delete("/deleteToDo/:id",auth,moduleController.deleteToDoList)
router.get("/groupBy",auth,moduleController.viewToDoListGroup)
module.exports=router